### ISSUE TITLE
Reference documentation

### ISSUE THREAD

**Issue by markbrough** [humportal/humportal#15]
We want to add a new section on the humportal site to capture documentation on how to publish various types of humanitarian data.

* add a new menu item to the main navigation bar called "How To Publish"
* within the "how to publish" section, add a secondary navigation for this section
* this section will contain a series of markdown files (which @markbrough will provide)

Once we have the basics up we will also want to add some charts into the reference documentation, but we can start with this for now!

**Comment by xarrijorge** [comment]
Should the secondary navigation be a drop down or an in page navigation?
