### ISSUE TITLE
Add traceability statistics

### ISSUE THREAD

**Issue by markbrough** [humportal/humportal#8]
We have just finished working on some new data on traceability, working with the team from Open Data Services. It would be great to add some of this information on to the individual publisher pages for now.

Below all the existing information on each publisher page, e.g.: https://humportal.org/signatory-data/GB-GOV-1

Let's add one row with two elements (left and right). All of the data comes from stats.codeforiati.org; but note that right now, for these two elements, we need to take data from stats-dev.codeforiati.org until the [related PR](https://github.com/codeforIATI/IATI-Stats/pull/34) is merged to main and then builds to the main site (which takes 4-6 hours).

### Left: **Traceable value of activities**
Pie chart comparing this file:
https://stats-dev.codeforiati.org/current/aggregated-publisher/fcdo/traceable_sum_commitments_and_disbursements_by_publisher_id.json
with this file:
https://stats-dev.codeforiati.org/current/aggregated-publisher/fcdo/traceable_sum_commitments_and_disbursements_by_publisher_id_denominator.json

In each case, replacing `fcdo` with the relevant `publisherID` (from `${this.publisher.publisherID}`)

### Right: **Traceable number of activities**

Pie chart comparing this file:
https://stats-dev.codeforiati.org/current/aggregated-publisher/fcdo/traceable_activities_by_publisher_id.json
with this file:
https://stats-dev.codeforiati.org/current/aggregated-publisher/fcdo/traceable_activities_by_publisher_id_denominator.json

In each case, replacing `fcdo` with the relevant `publisherID` (from `${this.publisher.publisherID}`)

**Comment by xarrijorge** [comment]
On the data page, under 'Traceability', there is already one pie chart. Should that stay as the 'left chart' and just add the right chart or is the data from a different source and need to be replaced?

**Comment by markbrough** [comment]
I think just leave everything that is there for now. And add this as a new element below. We can work out how to tidy things up later.
